name: typesafe_firebase_firestore_example
description: "A Flutter project for demostrating typesafe_firebase_firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  typesafe_firebase_core: ^0.0.3
  typesafe_firebase_firestore: ^0.0.3
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  typesafe_firebase_generator: ^0.0.4
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
